get-aduser assaab -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser awood -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser aljohnson -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser ahardiman -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser bmfelix -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser bjpeters -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser cmccauley -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser capfleger -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser clyoung -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser cjjohnson -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser cerondinelli -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser cmblack -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser dlcifelli -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser dddecker -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser djdrakesmith -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser dmiller -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser demorrison -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser dcflannery -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser dpmatthews -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser eastack -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser esboyce -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser esullivan -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser gmgaskin -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser gsledge -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser gkjain -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser glvilim -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser gsbolton -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser hlieb -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jamsosa -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jdaras -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jmcnicholas -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jtschmidt -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jashockey -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jmwebb -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jccaicco -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jlrowen -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jwilkinson -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jeremyoliver -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jbradbury -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jlsharp -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jncooke -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jdmezzasalma -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jrmorris -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jvrobinson -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jdreid -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jcyrus -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jbgoldstien -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser jsreicher -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser kdamore -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser krdyer -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser kegottschalk -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser krkanavel -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser kamatthews -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser krkowalski -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser kbkremstein -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lncookman -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lmacolino -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lacorrea -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lrhildreth -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lpinto -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser laaustin -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser lcsigillo -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser latarantino -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mjbuete -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mfoster -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mfahywoehr -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mdiperi -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mtadago -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mconway -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mmancino -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mmullarkey -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mpsgammato -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser mconway -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser nmmerrick -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser oamster -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser pgsitton -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser ppnair -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rhmadia -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rfgonzales -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rjlux -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rdbarone -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rmnicosia -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rlcifelli -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rjlyles -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rmaclaine -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser rmnorwood -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser russw -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser sastremlau -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser smbroughton -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser saralavery -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser smtomasso -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser sohunt -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser smflowers -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser slehman -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser sgozdan -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser staylor -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser smvyas -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser tmriley -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser tkbland -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser tjking -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser tquinn -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser tcarr -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser vsiadova -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser wchu -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser watull -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser wmoffett -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append
get-aduser wpriester -Properties * | Select-Object SamAccountName, Department | Export-Csv "C:\Temp\Results - Reviewers.csv" -NoTypeInformation -Append